[workspace]
members = ["projects/*"]
default-members = [
    "projects/awsl-vm",
    "projects/awsl-parser",
    "projects/awsl-ast",
    "projects/indent-formatter",
]

[profile.release]
lto = true
opt-level = "s"